init: |
  install /dev/stdin /workspace/bin/open.sh <<'EOF'
  #!/bin/bash
  exec gp preview --external "$@"
  EOF
command: |
  sudo update-alternatives --install /usr/bin/www-browser www-browser /workspace/bin/open.sh 100
