init: |
  tmpdir=$(mktemp -d)
  cd "$tmpdir" || exit
  wget https://app.conveyordata.com/api/info/cli/location/linux/amd64 -O c.tar.gz
  tar -zxvf c.tar.gz --one-top-level
  install c/bin/linux/amd64/conveyor /workspace/bin
  install c/bin/linux/amd64/datafy /workspace/bin
  cd || exit
  rm -r "$tmpdir"
