init: |
  tmp="$(mktemp -d)"
  cd "$tmp" || exit
  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
  echo "$(<kubectl.sha256)  kubectl" | sha256sum --check
  sudo install kubectl /usr/local/bin
  cd && rm -r "$tmp"
